---
- hosts: localhost
#  become: yes

  tasks:
  - name: create build directory for deployment artifacts
    file:
      path: "{{ openshift_build_path }}"
      state: directory
      mode: 0700

  - name: download and extract openshift installer
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-install-linux-{{ openshift_version }}.tar.gz
      dest: "{{ openshift_build_path }}"
      remote_src: yes

  - name: download and extract openshift oc cli tool
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/{{ openshift_version }}/openshift-client-linux-{{ openshift_version }}.tar.gz
      dest: "{{ openshift_build_path }}"
      remote_src: yes

#  - name: configure openshift oc command completion
#    shell: "{{ item }}"
#    loop:
#      - "{{ openshift_build_path }}/oc completion bash > oc_bash_completion"
#      - "cp oc_bash_completion /etc/bash_completion.d/"

  - name: extract openshift odo developer cli tool
    unarchive:
      src: https://mirror.openshift.com/pub/openshift-v4/clients/odo/v{{ openshift_odo_version }}/odo-linux-amd64.tar.gz
      dest: "{{ openshift_build_path }}"
      remote_src: yes

#  - name: configure openshift odo command completion
#    shell: "complete -o nospace -C {{ openshift_build_path }} odo"