---
- hosts: localhost

  tasks:

  - name: generate cluster ssh key pair
    openssh_keypair:
      path: "{{ openshift_build_path }}/{{ openshift_cluster_name }}-key"
      size: 4096
      type: rsa

  - debug:
      msg: Sequentially run the eval and ssh-add commands below.

  - debug:
      msg: eval $(ssh-agent -s)

  - debug:
      msg: "ssh-add {{ openshift_build_path }}/{{ openshift_cluster_name }}-key"
