---
- hosts: localhost

  tasks:
    - name: create openshift install-config.yaml file
      template:
        src: "{{ openshift_installer_path }}/roles/templates/install-config.yaml.j2"
        dest: "{{ openshift_build_path }}/install-config.yaml"

    - name: backup install-config.yaml file as install-config.yaml.backup
      copy:
        src: "{{ openshift_build_path }}/install-config.yaml"
        dest: "{{ openshift_build_path }}/install-config.yaml.backup"

    - debug:
        msg: execute the following command to deploy the openshift cluster

    - debug:
        msg: "{{ openshift_build_path }}/openshift-install create cluster --dir={{ openshift_build_path }} --log-level={{ openshift_installer_log_level }}"
