---
- hosts: localhost

  environment:
    KUBECONFIG: "{{ openshift_build_path }}/auth/kubeconfig"  # "{{ ansible_env.PWD }}/auth/kubeconfig"

  tasks:
    - name: Deploy OpenShift Service Mesh
      include_role:
        name: service-mesh
